export type Texture = {
  name: string
  slug: string
  category: string
  tag: string
  css: Record<string, string>
}

export const CATEGORIES = [
  "Geometric",
  "Woven & Fabric",
  "Nature & Organic",
  "Technical",
  "Decorative",
  "Experimental",
] as const

export const textures: Texture[] = [
  { name:"Crosshatch", slug:"crosshatch", category:"Geometric", tag:"Classic", css:{ backgroundImage:"repeating-linear-gradient(45deg,transparent,transparent 6px,currentColor 6px,currentColor 7px),repeating-linear-gradient(-45deg,transparent,transparent 6px,currentColor 6px,currentColor 7px)" }},
  { name:"Graph Paper", slug:"graph", category:"Geometric", tag:"Grid", css:{ backgroundImage:"repeating-linear-gradient(0deg,transparent,transparent 19px,currentColor 19px,currentColor 20px),repeating-linear-gradient(90deg,transparent,transparent 19px,currentColor 19px,currentColor 20px)" }},
  { name:"Grid Fine", slug:"grid-fine", category:"Geometric", tag:"Micro", css:{ backgroundImage:"repeating-linear-gradient(0deg,transparent,transparent 4px,currentColor 4px,currentColor 5px),repeating-linear-gradient(90deg,transparent,transparent 4px,currentColor 4px,currentColor 5px)" }},
  { name:"Dot Grid", slug:"dotgrid", category:"Geometric", tag:"Bujo", css:{ backgroundImage:"radial-gradient(circle,currentColor 1px,transparent 1px)", backgroundSize:"14px 14px" }},
  { name:"Dot Grid LG", slug:"dotgrid-lg", category:"Geometric", tag:"Open", css:{ backgroundImage:"radial-gradient(circle,currentColor 1.5px,transparent 1.5px)", backgroundSize:"22px 22px" }},
  { name:"Pin Stripe", slug:"pinstripe", category:"Geometric", tag:"Narrow", css:{ backgroundImage:"repeating-linear-gradient(90deg,transparent,transparent 11px,currentColor 11px,currentColor 12px)" }},
  { name:"Cabana Stripe", slug:"cabana", category:"Geometric", tag:"Wide", css:{ backgroundImage:"repeating-linear-gradient(90deg,transparent,transparent 18px,currentColor 18px,currentColor 20px)" }},
  { name:"Diagonal", slug:"diagonal", category:"Geometric", tag:"Bold", css:{ backgroundImage:"repeating-linear-gradient(45deg,transparent,transparent 8px,currentColor 8px,currentColor 10px)" }},
  { name:"Diagonal Fine", slug:"diagonal-fine", category:"Geometric", tag:"Hairline", css:{ backgroundImage:"repeating-linear-gradient(45deg,transparent,transparent 4px,currentColor 4px,currentColor 5px)" }},
  { name:"Checkerboard", slug:"checker", category:"Geometric", tag:"Small", css:{ backgroundImage:"repeating-linear-gradient(45deg,currentColor 25%,transparent 25%,transparent 75%,currentColor 75%,currentColor),repeating-linear-gradient(45deg,currentColor 25%,transparent 25%,transparent 75%,currentColor 75%,currentColor)", backgroundSize:"12px 12px", backgroundPosition:"0 0,6px 6px" }},
  { name:"Checkerboard LG", slug:"checker-lg", category:"Geometric", tag:"Large", css:{ backgroundImage:"repeating-linear-gradient(45deg,currentColor 25%,transparent 25%,transparent 75%,currentColor 75%,currentColor),repeating-linear-gradient(45deg,currentColor 25%,transparent 25%,transparent 75%,currentColor 75%,currentColor)", backgroundSize:"24px 24px", backgroundPosition:"0 0,12px 12px" }},
  { name:"Hash Mark", slug:"hash", category:"Geometric", tag:"Bold grid", css:{ backgroundImage:"repeating-linear-gradient(0deg,transparent,transparent 8px,currentColor 8px,currentColor 10px),repeating-linear-gradient(90deg,transparent,transparent 8px,currentColor 8px,currentColor 10px)", backgroundSize:"10px 10px" }},
  { name:"Argyle", slug:"argyle", category:"Geometric", tag:"Diamond", css:{ backgroundImage:"repeating-linear-gradient(45deg,currentColor 0,currentColor 1px,transparent 0,transparent 50%),repeating-linear-gradient(-45deg,currentColor 0,currentColor 1px,transparent 0,transparent 50%)", backgroundSize:"20px 20px" }},
  { name:"Herringbone", slug:"herringbone", category:"Woven & Fabric", tag:"Classic", css:{ backgroundImage:"repeating-linear-gradient(45deg,transparent,transparent 4px,currentColor 4px,currentColor 5px,transparent 5px,transparent 10px),repeating-linear-gradient(-45deg,transparent,transparent 4px,currentColor 4px,currentColor 5px,transparent 5px,transparent 10px)" }},
  { name:"Tartan", slug:"tartan", category:"Woven & Fabric", tag:"Plaid", css:{ backgroundImage:"repeating-linear-gradient(0deg,transparent,transparent 8px,currentColor 8px,currentColor 10px,transparent 10px,transparent 18px,currentColor 18px,currentColor 20px),repeating-linear-gradient(90deg,transparent,transparent 8px,currentColor 8px,currentColor 10px,transparent 10px,transparent 18px,currentColor 18px,currentColor 20px)", backgroundSize:"20px 20px" }},
  { name:"Weave", slug:"weave", category:"Woven & Fabric", tag:"Basket", css:{ backgroundImage:"repeating-linear-gradient(0deg,transparent,transparent 4px,currentColor 4px,currentColor 5px,transparent 5px,transparent 10px),repeating-linear-gradient(90deg,transparent,transparent 4px,currentColor 4px,currentColor 5px,transparent 5px,transparent 10px)", backgroundSize:"10px 10px", backgroundPosition:"0 0,5px 5px" }},
  { name:"Tweed", slug:"tweed", category:"Woven & Fabric", tag:"Layered", css:{ backgroundImage:"repeating-linear-gradient(45deg,transparent,transparent 2px,currentColor 2px,currentColor 3px),repeating-linear-gradient(-45deg,transparent,transparent 2px,currentColor 2px,currentColor 3px),repeating-linear-gradient(0deg,transparent,transparent 5px,currentColor 5px,currentColor 6px)" }},
  { name:"Linen", slug:"linen", category:"Woven & Fabric", tag:"Textile", css:{ backgroundImage:"repeating-linear-gradient(0deg,transparent,transparent 3px,currentColor 3px,currentColor 4px),repeating-linear-gradient(90deg,transparent,transparent 7px,currentColor 7px,currentColor 8px)" }},
  { name:"Seersucker", slug:"seersucker", category:"Woven & Fabric", tag:"Stripe", css:{ backgroundImage:"repeating-linear-gradient(90deg,transparent,transparent 5px,currentColor 5px,currentColor 6px,transparent 6px,transparent 11px,currentColor 11px,currentColor 12px,transparent 12px,transparent 17px,rgba(0,0,0,0.025) 17px,rgba(0,0,0,0.025) 22px)" }},
  { name:"Burlap", slug:"burlap", category:"Woven & Fabric", tag:"Rough", css:{ backgroundImage:"repeating-linear-gradient(0deg,transparent,transparent 2px,currentColor 2px,currentColor 3px),repeating-linear-gradient(90deg,transparent,transparent 2px,currentColor 2px,currentColor 3px),repeating-linear-gradient(45deg,transparent,transparent 5px,currentColor 5px,currentColor 6px)" }},
  { name:"Knit", slug:"knit", category:"Woven & Fabric", tag:"Tricot", css:{ backgroundImage:"repeating-linear-gradient(60deg,transparent,transparent 3px,currentColor 3px,currentColor 4px,transparent 4px,transparent 8px),repeating-linear-gradient(-60deg,transparent,transparent 3px,currentColor 3px,currentColor 4px,transparent 4px,transparent 8px),repeating-linear-gradient(0deg,transparent,transparent 7px,currentColor 7px,currentColor 8px)" }},
  { name:"Houndstooth", slug:"houndstooth", category:"Woven & Fabric", tag:"Couture", css:{ backgroundImage:"repeating-linear-gradient(45deg,currentColor 0px,currentColor 5px,transparent 5px,transparent 10px),repeating-linear-gradient(-45deg,currentColor 0px,currentColor 5px,transparent 5px,transparent 10px),repeating-linear-gradient(90deg,transparent,transparent 5px,currentColor 5px,currentColor 6px)" }},
  { name:"Carbon Fiber", slug:"carbon", category:"Woven & Fabric", tag:"Industrial", css:{ backgroundImage:"repeating-linear-gradient(135deg,transparent,transparent 4px,currentColor 4px,currentColor 5px),repeating-linear-gradient(45deg,transparent,transparent 4px,currentColor 4px,currentColor 5px)", backgroundSize:"8px 8px" }},
  { name:"Wood Grain", slug:"woodgrain", category:"Nature & Organic", tag:"Natural", css:{ backgroundImage:"repeating-linear-gradient(88deg,transparent,transparent 4px,currentColor 4px,currentColor 5px,transparent 5px,transparent 11px,currentColor 11px,currentColor 12px,transparent 12px,transparent 20px)" }},
  { name:"Bark", slug:"bark", category:"Nature & Organic", tag:"Rough grain", css:{ backgroundImage:"repeating-linear-gradient(85deg,transparent,transparent 2px,currentColor 2px,currentColor 3px,transparent 3px,transparent 9px),repeating-linear-gradient(92deg,transparent,transparent 2px,currentColor 2px,currentColor 3px,transparent 3px,transparent 13px)" }},
  { name:"Topographic", slug:"topographic", category:"Nature & Organic", tag:"Contour map", css:{ backgroundImage:"repeating-radial-gradient(ellipse at 50% 50%,transparent,transparent 10px,currentColor 10px,currentColor 11px),repeating-radial-gradient(ellipse at 20% 80%,transparent,transparent 14px,currentColor 14px,currentColor 15px)" }},
  { name:"Ripple", slug:"ripple", category:"Nature & Organic", tag:"Water rings", css:{ backgroundImage:"repeating-radial-gradient(circle at 50% 50%,transparent,transparent 6px,currentColor 6px,currentColor 7px)" }},
  { name:"Scales", slug:"scales", category:"Nature & Organic", tag:"Fish / reptile", css:{ backgroundImage:"radial-gradient(ellipse at 50% 0%,currentColor 30%,transparent 70%),radial-gradient(ellipse at 0% 50%,currentColor 30%,transparent 70%)", backgroundSize:"18px 18px", backgroundPosition:"0 0,9px 9px" }},
  { name:"Honeycomb", slug:"honeycomb", category:"Nature & Organic", tag:"Hex cells", css:{ backgroundImage:"repeating-linear-gradient(60deg,transparent,transparent 9px,currentColor 9px,currentColor 10px),repeating-linear-gradient(-60deg,transparent,transparent 9px,currentColor 9px,currentColor 10px),repeating-linear-gradient(0deg,transparent,transparent 9px,currentColor 9px,currentColor 10px)" }},
  { name:"Pebble", slug:"pebble", category:"Nature & Organic", tag:"Stone scatter", css:{ backgroundImage:"radial-gradient(circle at 25% 25%,currentColor 1px,transparent 6px),radial-gradient(circle at 75% 75%,currentColor 1px,transparent 6px),radial-gradient(circle at 55% 15%,currentColor 1px,transparent 5px),radial-gradient(circle at 15% 65%,currentColor 1px,transparent 5px)", backgroundSize:"24px 24px" }},
  { name:"Rain", slug:"rain", category:"Nature & Organic", tag:"Slant", css:{ backgroundImage:"repeating-linear-gradient(100deg,transparent,transparent 8px,currentColor 8px,currentColor 9px,transparent 9px,transparent 18px)" }},
  { name:"Sand", slug:"sand", category:"Nature & Organic", tag:"Micro dust", css:{ backgroundImage:"radial-gradient(circle,currentColor 0.5px,transparent 0.5px),radial-gradient(circle,currentColor 0.5px,transparent 0.5px),radial-gradient(circle,currentColor 0.5px,transparent 0.5px)", backgroundSize:"7px 7px,11px 11px,5px 5px", backgroundPosition:"0 0,3px 4px,5px 1px" }},
  { name:"Blueprint", slug:"blueprint", category:"Technical", tag:"Engineering", css:{ backgroundColor:"#1a2a4a", backgroundImage:"repeating-linear-gradient(0deg,transparent,transparent 29px,rgba(120,160,255,0.4) 29px,rgba(120,160,255,0.4) 30px),repeating-linear-gradient(90deg,transparent,transparent 29px,rgba(120,160,255,0.4) 29px,rgba(120,160,255,0.4) 30px),repeating-linear-gradient(0deg,transparent,transparent 5px,rgba(120,160,255,0.12) 5px,rgba(120,160,255,0.12) 6px),repeating-linear-gradient(90deg,transparent,transparent 5px,rgba(120,160,255,0.12) 5px,rgba(120,160,255,0.12) 6px)" }},
  { name:"Circuit Board", slug:"circuit", category:"Technical", tag:"PCB", css:{ backgroundImage:"repeating-linear-gradient(0deg,transparent,transparent 14px,currentColor 14px,currentColor 15px),repeating-linear-gradient(90deg,transparent,transparent 14px,currentColor 14px,currentColor 15px),radial-gradient(circle,currentColor 1.5px,transparent 1.5px)", backgroundSize:"15px 15px" }},
  { name:"Scanline", slug:"scanline", category:"Technical", tag:"CRT / TV", css:{ backgroundImage:"repeating-linear-gradient(0deg,transparent,transparent 2px,currentColor 2px,currentColor 3px)" }},
  { name:"Isometric", slug:"isometric", category:"Technical", tag:"3D grid", css:{ backgroundImage:"repeating-linear-gradient(30deg,transparent,transparent 9px,currentColor 9px,currentColor 10px),repeating-linear-gradient(-30deg,transparent,transparent 9px,currentColor 9px,currentColor 10px),repeating-linear-gradient(90deg,transparent,transparent 9px,currentColor 9px,currentColor 10px)" }},
  { name:"Ledger", slug:"ledger", category:"Technical", tag:"Accounting", css:{ backgroundImage:"repeating-linear-gradient(0deg,transparent,transparent 23px,currentColor 23px,currentColor 24px),repeating-linear-gradient(90deg,transparent,transparent 59px,currentColor 59px,currentColor 60px),repeating-linear-gradient(0deg,transparent,transparent 11px,rgba(0,0,0,0.025) 11px,rgba(0,0,0,0.025) 12px)" }},
  { name:"Ruled", slug:"ruled", category:"Technical", tag:"Notebook", css:{ backgroundImage:"repeating-linear-gradient(0deg,currentColor,currentColor 1px,transparent 1px,transparent 8px)" }},
  { name:"Moroccan", slug:"moroccan", category:"Decorative", tag:"Zellige", css:{ backgroundImage:"repeating-linear-gradient(60deg,transparent,transparent 8px,currentColor 8px,currentColor 9px),repeating-linear-gradient(-60deg,transparent,transparent 8px,currentColor 8px,currentColor 9px),repeating-linear-gradient(0deg,transparent,transparent 16px,currentColor 16px,currentColor 17px)" }},
  { name:"Starburst", slug:"starburst", category:"Decorative", tag:"Radiate", css:{ backgroundImage:"repeating-linear-gradient(0deg,transparent,transparent 9px,currentColor 9px,currentColor 10px),repeating-linear-gradient(30deg,transparent,transparent 9px,currentColor 9px,currentColor 10px),repeating-linear-gradient(60deg,transparent,transparent 9px,currentColor 9px,currentColor 10px)" }},
  { name:"Damask", slug:"damask", category:"Decorative", tag:"Ornate", css:{ backgroundImage:"repeating-linear-gradient(45deg,transparent,transparent 9px,currentColor 9px,currentColor 10px),repeating-linear-gradient(-45deg,transparent,transparent 9px,currentColor 9px,currentColor 10px),repeating-linear-gradient(0deg,transparent,transparent 18px,currentColor 18px,currentColor 19px),repeating-linear-gradient(90deg,transparent,transparent 18px,currentColor 18px,currentColor 19px)" }},
  { name:"Mosaic", slug:"mosaic", category:"Decorative", tag:"Tile art", css:{ backgroundImage:"repeating-linear-gradient(0deg,transparent,transparent 9px,currentColor 9px,currentColor 10px),repeating-linear-gradient(90deg,transparent,transparent 9px,currentColor 9px,currentColor 10px),radial-gradient(circle at 5px 5px,currentColor 1px,transparent 1px)", backgroundSize:"10px 10px" }},
  { name:"Floor Tiles", slug:"tiles", category:"Decorative", tag:"Stone", css:{ backgroundImage:"repeating-linear-gradient(0deg,currentColor,currentColor 1px,transparent 1px,transparent 20px),repeating-linear-gradient(90deg,currentColor,currentColor 1px,transparent 1px,transparent 20px),radial-gradient(circle at 10px 10px,currentColor 0.5px,transparent 0.5px)", backgroundSize:"20px 20px" }},
  { name:"Stars", slug:"stars", category:"Decorative", tag:"Celestial", css:{ backgroundImage:"radial-gradient(circle,currentColor 1px,transparent 1px),radial-gradient(circle,currentColor 0.5px,transparent 0.5px)", backgroundSize:"24px 24px,12px 12px", backgroundPosition:"0 0,6px 6px" }},
  { name:"Seigaiha", slug:"seigaiha", category:"Decorative", tag:"Japanese wave", css:{ backgroundImage:"radial-gradient(ellipse at 50% 0%,currentColor 50%,transparent 50%),radial-gradient(ellipse at 50% 0%,transparent 48%,currentColor 48%,currentColor 50%,transparent 50%)", backgroundSize:"20px 10px", backgroundPosition:"0 0,10px 10px" }},
  { name:"Noise", slug:"noise", category:"Experimental", tag:"Multi-angle", css:{ backgroundImage:"repeating-linear-gradient(17deg,transparent,transparent 3px,currentColor 3px,currentColor 4px),repeating-linear-gradient(-17deg,transparent,transparent 3px,currentColor 3px,currentColor 4px),repeating-linear-gradient(73deg,transparent,transparent 3px,currentColor 3px,currentColor 4px)" }},
  { name:"Optical", slug:"optical", category:"Experimental", tag:"Illusion", css:{ backgroundImage:"repeating-linear-gradient(0deg,transparent,transparent 5px,currentColor 5px,currentColor 6px),repeating-linear-gradient(90deg,transparent,transparent 5px,currentColor 5px,currentColor 6px),repeating-linear-gradient(45deg,transparent,transparent 5px,currentColor 5px,currentColor 6px)" }},
  { name:"Interference", slug:"interference", category:"Experimental", tag:"Moire", css:{ backgroundImage:"repeating-linear-gradient(45deg,transparent,transparent 3px,currentColor 3px,currentColor 4px),repeating-linear-gradient(90deg,transparent,transparent 7px,currentColor 7px,currentColor 8px),repeating-linear-gradient(135deg,transparent,transparent 11px,currentColor 11px,currentColor 12px)" }},
  { name:"Waves", slug:"waves", category:"Experimental", tag:"Flow", css:{ backgroundImage:"repeating-linear-gradient(0deg,transparent,transparent 8px,currentColor 8px,currentColor 9px),repeating-linear-gradient(30deg,transparent,transparent 8px,currentColor 8px,currentColor 9px)" }},
  { name:"Vortex", slug:"vortex", category:"Experimental", tag:"Radial chaos", css:{ backgroundImage:"repeating-radial-gradient(circle at 50% 50%,transparent,transparent 4px,currentColor 4px,currentColor 5px),repeating-linear-gradient(45deg,transparent,transparent 8px,currentColor 8px,currentColor 9px)" }},
]

export function getPrompt(t: Texture): string {
  const entries = Object.entries(t.css)
    .map(([k, v]) => `${k}: ${v};`)
    .join(" ")
  return `Pure CSS texture "${t.name}" (${t.category}): ${entries} Use with color: currentColor for theming.`
}
